import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const USER_AGENT = process.env.NWS_USER_AGENT || 'WaynesboroOS/1.0 (https://bmassey-brannen.github.io/waynesboro-os/; public civic dashboard)';

const FORECAST_URL = 'https://api.weather.gov/gridpoints/CAE/32,17/forecast';
const ALERTS_URL = 'https://api.weather.gov/alerts/active?zone=GAC033';

async function nwsJson(url) {
  const response = await fetch(url, {
    headers: {
      'Accept': 'application/geo+json, application/json',
      'User-Agent': USER_AGENT
    }
  });

  if (!response.ok) {
    const text = await response.text().catch(() => '');
    throw new Error(`NWS request failed ${response.status} for ${url}: ${text.slice(0, 300)}`);
  }

  return response.json();
}

function normalizeProbability(period) {
  const value = period?.probabilityOfPrecipitation?.value;
  return Number.isFinite(value) ? value : null;
}

function normalizeForecastPeriod(period) {
  return {
    number: period.number,
    name: period.name,
    startTime: period.startTime,
    endTime: period.endTime,
    temperature: period.temperature,
    temperatureUnit: period.temperatureUnit,
    windSpeed: period.windSpeed,
    windDirection: period.windDirection,
    shortForecast: period.shortForecast,
    probabilityOfPrecipitation: normalizeProbability(period),
    isDaytime: period.isDaytime
  };
}

function normalizeAlert(feature) {
  const properties = feature.properties || {};
  return {
    id: properties.id || feature.id || null,
    event: properties.event || 'NWS alert',
    headline: properties.headline || properties.event || 'NWS alert',
    severity: properties.severity || null,
    urgency: properties.urgency || null,
    certainty: properties.certainty || null,
    areaDesc: properties.areaDesc || null,
    effective: properties.effective || null,
    expires: properties.expires || null,
    instruction: properties.instruction || null,
    web: properties['@id'] || properties.id || null
  };
}

function writeModule(relativePath, exportName, snapshot) {
  const outPath = path.join(ROOT, relativePath);
  const content = `// Generated by scripts/fetch-weather.js.\n// Public NWS forecast/alert snapshot only; not dispatch, outage, or emergency-command telemetry.\n\nexport const ${exportName} = ${JSON.stringify(snapshot, null, 2)};\n`;
  fs.writeFileSync(outPath, content);
  console.log(`Weather snapshot written: ${outPath}`);
}

async function main() {
  const fetchedAt = new Date().toISOString();
  const [forecast, alerts] = await Promise.all([
    nwsJson(FORECAST_URL),
    nwsJson(ALERTS_URL)
  ]);

  const forecastPeriods = (forecast.properties?.periods || []).slice(0, 7).map(normalizeForecastPeriod);
  const generatedAt = forecast.properties?.generatedAt || forecast.properties?.updated || fetchedAt;

  writeModule('src/data/weatherForecastSnapshot.js', 'weatherForecastSnapshot', {
    provider: 'National Weather Service API / api.weather.gov',
    sourceName: 'NWS gridpoint forecast endpoint for Waynesboro point routing',
    sourceUrl: FORECAST_URL,
    geography: 'Waynesboro, Georgia point forecast routed to WFO CAE grid 32,17',
    accessMethod: 'Public NWS API with required User-Agent header; cached low-volume forecast periods only.',
    fetchedAt,
    generatedAt,
    updated: forecast.properties?.updated || null,
    status: 'verified_public_snapshot',
    periodCount: forecastPeriods.length,
    periods: forecastPeriods,
    summary: `Cached ${forecastPeriods.length} NWS forecast periods for the Waynesboro, Georgia point-routed grid. Use for public works/event-readiness context only after checking the timestamp.`,
    caveat: 'This is a cached public forecast snapshot, not an official emergency command feed, dispatch system, or live outage/incident monitor. Refreshed nightly by the public-site build workflow.'
  });

  const activeAlerts = (alerts.features || []).map(normalizeAlert);
  writeModule('src/data/weatherAlertsSnapshot.js', 'weatherAlertsSnapshot', {
    provider: 'National Weather Service API / api.weather.gov',
    sourceName: 'NWS active alerts endpoint for Burke County zone GAC033',
    sourceUrl: ALERTS_URL,
    geography: 'Burke County, Georgia alert zone GAC033',
    accessMethod: 'Public NWS API with required User-Agent header; low-volume cached snapshot only.',
    fetchedAt,
    status: 'verified_public_snapshot',
    featureCount: activeAlerts.length,
    title: alerts.title || 'Current watches, warnings, and advisories for Burke County (GAC033) GA',
    activeAlerts,
    summary: activeAlerts.length === 0
      ? `No active NWS watches, warnings, or advisories were returned for Burke County zone GAC033 at ${fetchedAt}.`
      : `${activeAlerts.length} active NWS alert(s) were returned for Burke County zone GAC033 at ${fetchedAt}.`,
    caveat: 'This is a cached public alert snapshot. It is not dispatch telemetry; use the linked NWS endpoint for the latest official alert status.'
  });
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
