#!/usr/bin/env python3
"""Low-volume Nominatim geocode helper for the public-demo downtown qPublic sample.
Writes only exact house/building matches; failed/street-level matches stay off-map.
"""
from __future__ import annotations

import json
import subprocess
import time
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CACHE_PATH = ROOT / "src/data/downtownParcelGeocodeSeed.js"
TMP_JSON = ROOT / ".tmp-downtown-map-parcels.json"

node_code = """
import { downtownParcelSeed } from './src/data/downtownParcelSeed.js';
console.log(JSON.stringify(downtownParcelSeed.mapParcels.map(p => ({ parcelId: p.parcelId, address: p.address }))));
"""
parcels = json.loads(subprocess.check_output(["node", "--input-type=module", "-e", node_code], cwd=ROOT, text=True))

existing = {}
if CACHE_PATH.exists():
    text = CACHE_PATH.read_text()
    marker = "export const downtownParcelGeocodeSeed = "
    if marker in text:
        body = text.split(marker, 1)[1].rsplit(";", 1)[0]
        try:
            for row in json.loads(body).get("geocodedParcels", []):
                existing[row["parcelId"]] = row
        except Exception:
            existing = {}

street_aliases = {
    "6TH STREET W": "West 6th Street",
    "6TH STREET E": "East 6th Street",
    "W 6TH STREET": "West 6th Street",
    "E 6TH STREET": "East 6th Street",
    "LIBERTY STREET": "Liberty Street",
    "N LIBERTY STREET": "North Liberty Street",
    "S LIBERTY STREET": "South Liberty Street",
}

def canonical_street(address: str) -> str:
    a = address.upper().replace("  ", " ")
    for key, val in street_aliases.items():
        if key in a:
            return val
    return ""

def expected_house(address: str) -> str:
    return address.split()[0]

def geocode(address: str):
    query = f"{address}, Waynesboro, GA 30830, United States"
    params = urllib.parse.urlencode({"q": query, "format": "jsonv2", "limit": 3, "addressdetails": 1})
    req = urllib.request.Request(
        f"https://nominatim.openstreetmap.org/search?{params}",
        headers={"User-Agent": "WaynesboroOS-public-demo-geocode/0.1 (low-volume local research)"},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        results = json.load(r)
    house = expected_house(address)
    street = canonical_street(address).lower()
    for item in results:
        addr = item.get("address", {})
        item_house = str(addr.get("house_number", ""))
        road = str(addr.get("road", "")).lower()
        osm_type = item.get("type", "")
        if item_house == house and (not street or street in road or road in street) and osm_type in {"house", "building", "yes", "commercial", "retail", "office"}:
            return {
                "parcelId": None,
                "address": address,
                "lat": round(float(item["lat"]), 7),
                "lon": round(float(item["lon"]), 7),
                "geocodeSource": "OpenStreetMap/Nominatim",
                "geocodeMatch": "exact-house-address",
                "osmType": item.get("osm_type"),
                "osmId": item.get("osm_id"),
                "displayName": item.get("display_name"),
            }
    return None

out = dict(existing)
for i, parcel in enumerate(parcels, 1):
    pid = parcel["parcelId"]
    if pid in out:
        continue
    try:
        hit = geocode(parcel["address"])
    except Exception as exc:
        print(f"{i}/{len(parcels)} ERROR {parcel['address']}: {exc}", flush=True)
        time.sleep(1.1)
        continue
    if hit:
        hit["parcelId"] = pid
        out[pid] = hit
        print(f"{i}/{len(parcels)} HIT {parcel['address']} -> {hit['lat']},{hit['lon']}", flush=True)
    else:
        print(f"{i}/{len(parcels)} MISS {parcel['address']}", flush=True)
    time.sleep(1.1)

payload = {
    "sourceName": "OpenStreetMap/Nominatim exact house-address geocodes for qPublic parcel sample",
    "status": "Exact house-address matches only; street-level or failed geocodes are intentionally excluded from map overlay.",
    "geocodedCount": len(out),
    "totalMapParcelRows": len(parcels),
    "geocodedParcels": sorted(out.values(), key=lambda r: (r["address"], r["parcelId"])),
}
CACHE_PATH.write_text("// Generated by scripts/geocode-downtown-parcels.py. Do not hand-edit.\n" + "export const downtownParcelGeocodeSeed = " + json.dumps(payload, indent=2) + ";\n")
print(f"WROTE {CACHE_PATH} exact geocodes={len(out)} of {len(parcels)}")
